dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3
base_dir = /run/dovecot
state_dir = /run/dovecot
protocols = imap
listen = *
ssl = no
auth_allow_cleartext = yes
auth_mechanisms = plain login
default_internal_user = vmail
default_login_user = vmail
default_internal_group = vmail
mail_uid = vmail
mail_gid = vmail
mail_driver = maildir
mailbox_list_layout = index
mail_path = ~/mail
mail_home = /srv/vmail/%{user | lower}
log_path = /dev/stdout
passdb static {
  password = woot59-synthetic-only
}
userdb static {
  fields {
    uid = 1000
    gid = 1000
    home = /srv/vmail/%{user | lower}
  }
}
namespace inbox {
  inbox = yes
  separator = /
}
service imap-login {
  process_min_avail = 0
  inet_listener imap {
    port = 31143
  }
  inet_listener imaps {
    port = 0
  }
}
